version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-url_shortener}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1d}
      - PORT=3000
      - BASE_URL=${BASE_URL:-http://localhost:3000}
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:14-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-url_shortener}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
